#%RAML 1.0 NamedExample
{
  username: test1,
  password: test,
  oauth2token: {"access_token":"KxbEy6n6cyysdw5xHe-pVW8_T0QXuJa-CjmuDQqGwelHHB3Eulzd23i4H4E-JmW3owg4gzT5r1cRm8AIHPSwvw","token_type":"Bearer","expires_in":86400}
}