#%RAML 1.0
title: greeting-api

uses:
  apiLib: datatypes/apilib.raml

/ping:
  get:
    description: ping
    queryParameters:
      username:
        description: username
        type: apiLib.username
        required: false
      password:
        description: password
        type: apiLib.password
        required: false
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              english: !include examples/test1.raml
              spanish: !include examples/test2.raml

/register:
  post:
    description: register
    body:
        application/json:
          type:  apiLib.regsiter
          example: |
            {
              "username": "test1",
              "password": "test"
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              english: !include examples/test1.raml
              spanish: !include examples/test2.raml

/login:
  post:
    description: login
    body:
        application/json:
          type:  apiLib.login
          example: |
            {
              "username": "test1",
              "password": "test"
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              english: !include examples/test1.raml
              spanish: !include examples/test2.raml