#%RAML 1.0
title: e-store-express-mule

uses:
  apiLib: datatypes/apilib.raml

/ping:
  get:
    description: ping
    queryParameters:
      username:
        description: username
        type: apiLib.username
        required: false
      password:
        description: password
        type: apiLib.password
        required: false
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/test1.raml
              example2: !include examples/test2.raml

/register:
  post:
    description: register
    body:
        application/json:
          type:  apiLib.regsiter
          example: |
            {
              "username": "test1",
              "password": "test",
              "name": "test1"
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/register/test1.raml
              example2: !include examples/register/test2.raml

/login:
  post:
    description: login
    body:
        application/json:
          type:  apiLib.login
          example: |
            {
              "username": "test1",
              "password": "test"
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/test1.raml
              example2: !include examples/test2.raml
/deleteuser:
  post:
    description: delete
    headers: 
      Authorization: 
        displayName: Authorization
        description: Bearer Token
        type: string
        required: true
    body:
        application/json:
          type:  apiLib.deleteuser
          example: |
            {
              "username": "test1",
              "name": "test1"
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/deleteuser/test1.raml
/getuser:
  get:
    description: getuser
    headers: 
      Authorization: 
        displayName: Authorization
        description: Bearer Token
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/getuser/test1.raml
